### ISSUE TITLE
Maven extensions keeps logging `WARNING: Failed to export metrics` when disabled

### ISSUE THREAD

**Issue by XN137** [open-telemetry/opentelemetry-java-contrib#1227] opened 2024-03-14 11:37 UTC
### Component(s)

maven-extension

### What happened?

in our build we are using the extension in `.mvn/extensions.xml`:
```
<extensions>
    (...)
    <extension>
      <!-- Disabled by default.
           Check https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/maven-extension for configuration.
      -->
      <groupId>io.opentelemetry.contrib</groupId>
      <artifactId>opentelemetry-maven-extension</artifactId>
      <!-- https://github.com/open-telemetry/opentelemetry-java-contrib/releases -->
      <version>1.31.0-alpha</version>
    </extension>
</extensions>
```

according to https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/maven-extension/README.md the exporter is `none` by default which should be a "no-op".
we only set an exporter in CI runs.

BUT for local builds we keep seeing these warnings:
```
[INFO] --- compiler:3.12.1:testCompile (default-testCompile) @ my-module-name ---
[INFO] Compiling 937 source files with javac [debug release 11] to target/test-classes
Mar 14, 2024 12:26:46 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/127.0.0.1:4317
```

it is totally not cool to try and send data anywhere when things should be disabled.
also these warnings are annoying/misleading.

please make no-op a true no-op... no gathering of data, no exporting of data anywhere.

### Component version

1.31.0-alpha

**Comment by cyrille-leclerc** [comment] 2024-04-12 09:38
Can you please indicate which version of Maven you are your using?

**Comment by XN137** [comment] 2024-04-12 09:40
we are using `3.9.6` via maven wrapper

**Comment by cyrille-leclerc** [comment] 2024-04-12 09:41
Thanks, is it a regression or a problem you have always seen?

**Comment by XN137** [comment] 2024-04-12 09:42
always seen afaict

**Comment by cyrille-leclerc** [comment] 2024-04-13 12:35
Problem was when the OTel Java SDK AutoConfigure changed the default of `otel.metrics.exporter` from `none` to `otlp`.

**Comment by cyrille-leclerc** [comment] 2024-04-16 08:14
@XN137 the OTel Maven extension doesn't produce OpnTelemetry metrics or logs. Could you have used the OTel Maven extension in conjunction with adding the Otel Java Agent through the Maven JVM startup parameters?

Note that a fix is in progress on:
* https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1276

**Comment by XN137** [comment] 2024-04-17 16:31
@cyrille-leclerc i dont think our build uses any other plugin or extension directly related to otel, so the answer is most likely no.

our product code generally uses otel and one of the product jars gets loaded through through `exec-maven-plugin` as part of the build, but not intentionally doing anything with otel.

wondering: were you not able to reproduce these warnings or why does it matter what our build does in terms of merging your changes?

thanks!

**Comment by cyrille-leclerc** [comment] 2024-05-07 10:00
Sorry for the delay.

I cannot reproduce on my SpringBoot test app but #1276 is definitely a change we have to roll out and it's likely to fix your problem.

Can you please enable an otel collector and list the metrics that are generated to help us understand the cause of the problem?

**Comment by XN137** [comment] 2024-05-08 08:15
can you provide details on how to get that list?

**Comment by cyrille-leclerc** [comment] 2024-05-12 17:33
A solution to list the produced OTel metrics is to connect the Maven build to a local OTel Collector that uses a metrics pipeline with a "[Prometheus Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter)".

After your Maven build has run, you can list all the produced metrics looking at the Prometheus page `http://localhost:8889/metrics`


```
  prometheus:
    endpoint: 127.0.0.1:8889
    resource_to_telemetry_conversion:
      enabled: true
```

**Comment by XN137** [comment] 2024-06-03 13:46
after upgrading `opentelemetry-maven-extension` to `1.36.0-alpha` in our `.mvn/extensions.xml` local builds seem to no longer log the mentioned warnings

@cyrille-leclerc thanks for the update, we can most likely close this ticket now?

**Comment by cyrille-leclerc** [comment] 2024-06-04 09:39
Thanks I'm closing

**Closed by cyrille-leclerc** 2024-06-04 09:39 UTC
Labels: component: maven-extension
