### ISSUE TITLE
AWS X-Ray trace ID format is wrong

### ISSUE THREAD

**Issue by YarivHastilow** [open-telemetry/opentelemetry-java-contrib#310] opened 2022-04-20 09:06 UTC
The [AwsXrayIdGenerator](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayIdGenerator.java) generates trace IDs as 32-digit hex strings.
These do not work in AWS X-Ray because it requires the trace ID to include version number and hyphens.

The  description in the Java file says: "Generates tracing ids compatible with the AWS X-Ray tracing service. In the X-Ray system the first 32 bits of the trace id are the Unix epoch time in secords."
"@see \<a href="https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html#xray-api-traceids">Generating
Trace IDs\</a>"

The description matches the code, but the linked page contradicts it, saying: "A trace_id consists of three numbers separated by hyphens. For example, 1-58406520-a006649127e371903a2de979."

I can confirm that the generated IDs do not work in X-Ray, but they will work if "1-" is prefixed and "-" inserted after the 8th character.

**Comment by anuraaga** [comment] 2022-04-20 09:14
Hi @YarivHastilow - the OpenTelemetry collector formats the ID before sending to X-Ray so things should generally work. If you're trying to query the traces in the console, perhaps because of doing log mdc injection, you will want to use the x-ray formatted one available in the aws distro. Some background here

https://github.com/aws-observability/aws-otel-java-instrumentation/issues/38

Closing this issue since the ID generator is working as intended, if anything is still unclear please file in the aws repo. Thanks.

**Closed** 2022-04-20 09:14 UTC
Labels: bug

**Comment by SeraphicRav** [comment] 2022-04-21 00:33
@anuraaga But if we call some in AWS like an API Gateway, it won't understand the traceId a create a new one, right ?

**Comment by anuraaga** [comment] 2022-04-21 00:48
Hi @SeraphicRav - For use with API gateway, you will need to use the xray propagator. The aws distro will enable this by default if you use it.

There is some work on supporting w3c in API gateway and other services but it will take a long time still I think.

**Comment by SeraphicRav** [comment] 2022-04-21 01:12
Hi @anuraaga, thanks for your answer
